-- STELLAR LEGACY V3 - banco preparado para facção, hangar, loja, inventário e drones
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  callsign text not null default 'Pilot',
  faction text,
  level int not null default 1,
  xp bigint not null default 0,
  credits bigint not null default 20000,
  premium bigint not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.player_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  map_id text not null default 'x1',
  x double precision default 380,
  y double precision default 900,
  hp bigint default 104000,
  shield bigint default 1000,
  active_ship_id text default 'phoenix',
  selected_laser_ammo text default 'lcb10',
  selected_rocket text default 'r310',
  flags jsonb not null default '{"autoLaser":false,"autoRocket":false,"turboRocket":false}'::jsonb,
  updated_at timestamptz default now()
);


-- Migração segura caso a V1/V2 já tenha criado essas tabelas
alter table public.profiles add column if not exists updated_at timestamptz default now();
alter table public.profiles alter column faction drop default;
alter table public.profiles alter column credits set default 20000;
alter table public.player_state alter column map_id set default 'x1';
alter table public.player_state alter column hp set default 104000;
alter table public.player_state alter column shield set default 1000;
alter table public.player_state add column if not exists active_ship_id text default 'phoenix';
alter table public.player_state add column if not exists selected_laser_ammo text default 'lcb10';
alter table public.player_state add column if not exists selected_rocket text default 'r310';
alter table public.player_state add column if not exists flags jsonb not null default '{"autoLaser":false,"autoRocket":false,"turboRocket":false}'::jsonb;

create table if not exists public.owned_ships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ship_id text not null,
  acquired_at timestamptz default now(),
  unique(user_id, ship_id)
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  quantity bigint not null default 1 check (quantity >= 0),
  unique(user_id, item_id)
);

create table if not exists public.ammunition (
  user_id uuid primary key references auth.users(id) on delete cascade,
  laser_ammo jsonb not null default '{"lcb10":10000,"mcb25":0,"mcb50":0,"ucb100":0}'::jsonb,
  rockets jsonb not null default '{"r310":100,"plt2026":0,"plt2021":0,"plt3030":0}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.ship_loadout (
  user_id uuid primary key references auth.users(id) on delete cascade,
  ship_id text not null default 'phoenix',
  lasers jsonb not null default '["lf1"]'::jsonb,
  generators jsonb not null default '["sg3na01"]'::jsonb,
  extras jsonb not null default '[]'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.player_drones (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  drone_type text not null check (drone_type in ('flax','iris')),
  position int not null check (position between 1 and 8),
  slots jsonb not null default '[]'::jsonb,
  created_at timestamptz default now(),
  unique(user_id, position)
);

-- Compatibilidade com a tabela antiga da V1/V2
create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  item_id text not null,
  quantity bigint not null default 1,
  slot text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.player_state enable row level security;
alter table public.owned_ships enable row level security;
alter table public.inventory_items enable row level security;
alter table public.ammunition enable row level security;
alter table public.ship_loadout enable row level security;
alter table public.player_drones enable row level security;
alter table public.inventory enable row level security;

drop policy if exists "own profile" on public.profiles;
drop policy if exists "own state" on public.player_state;
drop policy if exists "own ships" on public.owned_ships;
drop policy if exists "own inventory items" on public.inventory_items;
drop policy if exists "own ammunition" on public.ammunition;
drop policy if exists "own loadout" on public.ship_loadout;
drop policy if exists "own drones" on public.player_drones;
drop policy if exists "own inventory" on public.inventory;

create policy "own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "own state" on public.player_state for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own ships" on public.owned_ships for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own inventory items" on public.inventory_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own ammunition" on public.ammunition for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own loadout" on public.ship_loadout for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own drones" on public.player_drones for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own inventory" on public.inventory for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
