import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
app.use(express.json());
app.use(express.static(path.join(__dirname,'../public')));
app.get('/health',(req,res)=>res.json({ok:true,game:'Stellar Legacy',version:'3.0.0'}));
app.get('/api/meta',(req,res)=>res.json({name:'Stellar Legacy',version:'3.0.0',features:['factions','shop','owned_ships','equipment_slots','inventory','drones','ammo','rockets','x1_x4_maps']}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`Stellar Legacy V3 on :${port}`));
