-- Stellar Legacy — Admin Control Panel
-- Segurança: todas as ações verificam public.game_admins no servidor/banco.

create table if not exists public.account_moderation_v1763 (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_banned boolean not null default false,
  banned_until timestamptz,
  banned_reason text,
  banned_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_action_log_v1763 (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid,
  target_callsign text,
  target_email text,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.account_moderation_v1763 enable row level security;
alter table public.admin_action_log_v1763 enable row level security;
revoke all on public.account_moderation_v1763, public.admin_action_log_v1763 from anon, authenticated;

create or replace function public.is_game_admin_v1763(p_uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public,auth,pg_temp as $$
  select coalesce(exists(
    select 1 from public.game_admins ga
    where ga.user_id=p_uid and lower(coalesce(ga.role,''))='admin'
  ),false);
$$;

create or replace function public.get_my_account_access_v1763()
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_uid uuid:=auth.uid();
  v_row public.account_moderation_v1763%rowtype;
  v_active boolean:=false;
begin
  if v_uid is null then raise exception 'Sessão inválida.'; end if;
  select * into v_row from public.account_moderation_v1763 where user_id=v_uid;
  if found then
    v_active:=v_row.is_banned and (v_row.banned_until is null or v_row.banned_until>now());
    if v_row.is_banned and not v_active then
      update public.account_moderation_v1763
      set is_banned=false,banned_reason=null,banned_by=null,updated_at=now()
      where user_id=v_uid;
    end if;
  end if;
  return jsonb_build_object(
    'allowed',not v_active,
    'is_banned',v_active,
    'banned_until',case when v_active then v_row.banned_until else null end,
    'reason',case when v_active then v_row.banned_reason else null end
  );
end;$$;

create or replace function public.admin_status_v1763()
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_uid uuid:=auth.uid();
  v_admin boolean:=false;
  v_total bigint:=0;
  v_banned bigint:=0;
  v_online bigint:=0;
begin
  if v_uid is null then raise exception 'Sessão inválida.'; end if;
  v_admin:=public.is_game_admin_v1763(v_uid);
  if not v_admin then return jsonb_build_object('is_admin',false); end if;
  select count(*) into v_total from auth.users where deleted_at is null;
  select count(*) into v_banned from public.account_moderation_v1763 where is_banned and (banned_until is null or banned_until>now());
  select count(*) into v_online from public.player_presence where updated_at>now()-interval '2 minutes';
  return jsonb_build_object('is_admin',true,'total_accounts',v_total,'banned_accounts',v_banned,'online_accounts',v_online);
end;$$;

create or replace function public.admin_search_accounts_v1763(p_query text default '')
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_uid uuid:=auth.uid();
  v_q text:=lower(trim(coalesce(p_query,'')));
  v_rows jsonb;
begin
  if not public.is_game_admin_v1763(v_uid) then raise exception 'Acesso administrativo negado.'; end if;
  select coalesce(jsonb_agg(row_to_json(x) order by x.callsign,x.email),'[]'::jsonb) into v_rows
  from (
    select
      u.id::text as user_id,
      coalesce(p.callsign,split_part(coalesce(u.email,''),'@',1),'Pilot') as callsign,
      coalesce(u.email,'') as email,
      p.faction,
      coalesce(p.level,1) as level,
      coalesce(p.xp,0) as xp,
      coalesce(p.credits,0) as credits,
      coalesce(p.uridium,0) as uridium,
      (gs.user_id is not null) as has_save,
      public.is_game_admin_v1763(u.id) as is_admin,
      (coalesce(m.is_banned,false) and (m.banned_until is null or m.banned_until>now())) as is_banned,
      m.banned_until,
      m.banned_reason,
      u.created_at,
      pp.updated_at as presence_updated_at
    from auth.users u
    left join public.profiles p on p.id=u.id
    left join public.game_saves gs on gs.user_id=u.id
    left join public.account_moderation_v1763 m on m.user_id=u.id
    left join public.player_presence pp on pp.user_id=u.id
    where u.deleted_at is null and (
      v_q='' or lower(coalesce(p.callsign,'')) like '%'||v_q||'%'
      or lower(coalesce(u.email,'')) like '%'||v_q||'%'
      or lower(u.id::text) like '%'||v_q||'%'
    )
    order by coalesce(pp.updated_at,u.created_at) desc
    limit 30
  ) x;
  return jsonb_build_object('users',v_rows);
end;$$;

create or replace function public.admin_recent_actions_v1763()
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_uid uuid:=auth.uid(); v_rows jsonb;
begin
  if not public.is_game_admin_v1763(v_uid) then raise exception 'Acesso administrativo negado.'; end if;
  select coalesce(jsonb_agg(row_to_json(x) order by x.created_at desc),'[]'::jsonb) into v_rows
  from (
    select id,target_user_id::text,target_callsign,target_email,action,detail,created_at
    from public.admin_action_log_v1763
    order by created_at desc limit 40
  ) x;
  return jsonb_build_object('actions',v_rows);
end;$$;

create or replace function public.admin_set_ban_v1763(p_target_user_id uuid,p_minutes integer default null,p_reason text default null)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_admin uuid:=auth.uid();
  v_callsign text;
  v_email text;
  v_until timestamptz;
begin
  if not public.is_game_admin_v1763(v_admin) then raise exception 'Acesso administrativo negado.'; end if;
  if p_target_user_id is null then raise exception 'Conta inválida.'; end if;
  if p_target_user_id=v_admin then raise exception 'Você não pode banir a própria conta administrativa.'; end if;
  if public.is_game_admin_v1763(p_target_user_id) then raise exception 'Outra conta administrativa não pode ser banida por este painel.'; end if;
  select coalesce(p.callsign,split_part(coalesce(u.email,''),'@',1),'Pilot'),coalesce(u.email,'')
    into v_callsign,v_email from auth.users u left join public.profiles p on p.id=u.id where u.id=p_target_user_id and u.deleted_at is null;
  if not found then raise exception 'Conta não encontrada.'; end if;
  v_until:=case when coalesce(p_minutes,0)<=0 then null else now()+make_interval(mins=>greatest(1,least(p_minutes,525600))) end;
  insert into public.account_moderation_v1763(user_id,is_banned,banned_until,banned_reason,banned_by,updated_at)
  values(p_target_user_id,true,v_until,left(nullif(trim(coalesce(p_reason,'')),''),240),v_admin,now())
  on conflict(user_id) do update set is_banned=true,banned_until=excluded.banned_until,banned_reason=excluded.banned_reason,banned_by=v_admin,updated_at=now();
  delete from public.game_login_sessions_v1214 where user_id=p_target_user_id;
  delete from public.player_presence where user_id=p_target_user_id;
  insert into public.admin_action_log_v1763(admin_user_id,target_user_id,target_callsign,target_email,action,detail)
  values(v_admin,p_target_user_id,v_callsign,v_email,'ban',jsonb_build_object('minutes',p_minutes,'until',v_until,'reason',left(coalesce(p_reason,''),240)));
  return jsonb_build_object('ok',true,'user_id',p_target_user_id,'callsign',v_callsign,'banned_until',v_until);
end;$$;

create or replace function public.admin_unban_user_v1763(p_target_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_admin uuid:=auth.uid(); v_callsign text; v_email text;
begin
  if not public.is_game_admin_v1763(v_admin) then raise exception 'Acesso administrativo negado.'; end if;
  select coalesce(p.callsign,split_part(coalesce(u.email,''),'@',1),'Pilot'),coalesce(u.email,'') into v_callsign,v_email
    from auth.users u left join public.profiles p on p.id=u.id where u.id=p_target_user_id and u.deleted_at is null;
  if not found then raise exception 'Conta não encontrada.'; end if;
  insert into public.account_moderation_v1763(user_id,is_banned,banned_until,banned_reason,banned_by,updated_at)
  values(p_target_user_id,false,null,null,null,now())
  on conflict(user_id) do update set is_banned=false,banned_until=null,banned_reason=null,banned_by=null,updated_at=now();
  insert into public.admin_action_log_v1763(admin_user_id,target_user_id,target_callsign,target_email,action)
  values(v_admin,p_target_user_id,v_callsign,v_email,'unban');
  return jsonb_build_object('ok',true,'user_id',p_target_user_id,'callsign',v_callsign);
end;$$;

create or replace function public.admin_transfer_owned_clan_v1763(p_target_user_id uuid)
returns void language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_clan uuid; v_next uuid;
begin
  for v_clan in select id from public.clans where owner_id=p_target_user_id loop
    select cm.user_id into v_next from public.clan_members cm
      where cm.clan_id=v_clan and cm.user_id<>p_target_user_id
      order by cm.joined_at asc limit 1;
    if v_next is null then
      delete from public.clans where id=v_clan;
    else
      update public.clans set owner_id=v_next,updated_at=now() where id=v_clan;
      update public.clan_members set role='member' where clan_id=v_clan and user_id=p_target_user_id;
      update public.clan_members set role='owner' where clan_id=v_clan and user_id=v_next;
    end if;
  end loop;
end;$$;

create or replace function public.admin_reset_account_v1763(p_target_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_admin uuid:=auth.uid();
  v_callsign text;
  v_email text;
begin
  if not public.is_game_admin_v1763(v_admin) then raise exception 'Acesso administrativo negado.'; end if;
  if p_target_user_id is null then raise exception 'Conta inválida.'; end if;
  if public.is_game_admin_v1763(p_target_user_id) then raise exception 'Conta administrativa protegida contra reset total.'; end if;
  select coalesce(p.callsign,split_part(coalesce(u.email,''),'@',1),'Pilot'),coalesce(u.email,'') into v_callsign,v_email
    from auth.users u left join public.profiles p on p.id=u.id where u.id=p_target_user_id and u.deleted_at is null;
  if not found then raise exception 'Conta não encontrada.'; end if;

  perform public.admin_transfer_owned_clan_v1763(p_target_user_id);
  delete from public.clan_members where user_id=p_target_user_id;
  delete from public.clan_credit_grants where sender_id=p_target_user_id or recipient_id=p_target_user_id;
  delete from public.clan_transactions where actor_id=p_target_user_id;
  update public.clan_transactions set target_user_id=null where target_user_id=p_target_user_id;
  delete from public.clan_war_contrib_v131 where user_id=p_target_user_id;
  delete from public.world_boss_claims_v131 where user_id=p_target_user_id;
  delete from public.world_boss_contrib_v131 where user_id=p_target_user_id;

  delete from public.pvp_damage_events where target_user_id=p_target_user_id or attacker_user_id=p_target_user_id;
  delete from public.pvp_engagements where home_user_id=p_target_user_id or invader_user_id=p_target_user_id;
  delete from public.arena_battles where attacker_id=p_target_user_id or defender_id=p_target_user_id or winner_id=p_target_user_id;
  delete from public.arena_daily_rewards where user_id=p_target_user_id;
  delete from public.arena_daily where user_id=p_target_user_id;
  delete from public.arena_stats where user_id=p_target_user_id;
  delete from public.arena_profiles where user_id=p_target_user_id;

  delete from public.designer_drop_claims_v16 where user_id=p_target_user_id;
  delete from public.player_drone_designs_v16 where user_id=p_target_user_id;
  delete from public.player_design_loadout_v16 where user_id=p_target_user_id;
  delete from public.player_design_inventory_v16 where user_id=p_target_user_id;

  delete from public.auction_bids where user_id=p_target_user_id;
  delete from public.player_presence where user_id=p_target_user_id;
  delete from public.game_login_sessions_v1214 where user_id=p_target_user_id;
  delete from public.game_saves where user_id=p_target_user_id;
  delete from public.player_state where user_id=p_target_user_id;
  delete from public.owned_ships where user_id=p_target_user_id;
  delete from public.inventory_items where user_id=p_target_user_id;
  delete from public.ammunition where user_id=p_target_user_id;
  delete from public.ship_loadout where user_id=p_target_user_id;
  delete from public.player_drones where user_id=p_target_user_id;
  delete from public.inventory where user_id=p_target_user_id;

  update public.profiles set faction=null,level=1,xp=0,credits=20000,uridium=0,aliens_killed=0,gg_completed=0,updated_at=now()
    where id=p_target_user_id;

  insert into public.admin_action_log_v1763(admin_user_id,target_user_id,target_callsign,target_email,action,detail)
  values(v_admin,p_target_user_id,v_callsign,v_email,'reset',jsonb_build_object('premium_preserved',true,'callsign_preserved',true));
  return jsonb_build_object('ok',true,'user_id',p_target_user_id,'callsign',v_callsign,'message','Conta zerada. Login e identidade preservados.');
end;$$;

create or replace function public.admin_delete_account_v1763(p_target_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare
  v_admin uuid:=auth.uid();
  v_callsign text;
  v_email text;
begin
  if not public.is_game_admin_v1763(v_admin) then raise exception 'Acesso administrativo negado.'; end if;
  if p_target_user_id is null then raise exception 'Conta inválida.'; end if;
  if p_target_user_id=v_admin then raise exception 'Você não pode deletar a própria conta administrativa.'; end if;
  if public.is_game_admin_v1763(p_target_user_id) then raise exception 'Outra conta administrativa não pode ser deletada por este painel.'; end if;
  select coalesce(p.callsign,split_part(coalesce(u.email,''),'@',1),'Pilot'),coalesce(u.email,'') into v_callsign,v_email
    from auth.users u left join public.profiles p on p.id=u.id where u.id=p_target_user_id and u.deleted_at is null;
  if not found then raise exception 'Conta não encontrada.'; end if;

  perform public.admin_transfer_owned_clan_v1763(p_target_user_id);
  insert into public.admin_action_log_v1763(admin_user_id,target_user_id,target_callsign,target_email,action,detail)
  values(v_admin,p_target_user_id,v_callsign,v_email,'delete',jsonb_build_object('account_deleted',true));
  delete from auth.users where id=p_target_user_id;
  if not found then raise exception 'Falha ao deletar a conta.'; end if;
  return jsonb_build_object('ok',true,'user_id',p_target_user_id,'callsign',v_callsign,'message','Conta deletada. O jogador terá que criar uma nova conta.');
end;$$;

revoke all on function public.is_game_admin_v1763(uuid) from public,anon;
revoke all on function public.get_my_account_access_v1763() from public,anon;
revoke all on function public.admin_status_v1763() from public,anon;
revoke all on function public.admin_search_accounts_v1763(text) from public,anon;
revoke all on function public.admin_recent_actions_v1763() from public,anon;
revoke all on function public.admin_set_ban_v1763(uuid,integer,text) from public,anon;
revoke all on function public.admin_unban_user_v1763(uuid) from public,anon;
revoke all on function public.admin_transfer_owned_clan_v1763(uuid) from public,anon,authenticated;
revoke all on function public.admin_reset_account_v1763(uuid) from public,anon;
revoke all on function public.admin_delete_account_v1763(uuid) from public,anon;

grant execute on function public.is_game_admin_v1763(uuid) to authenticated,service_role;
grant execute on function public.get_my_account_access_v1763() to authenticated,service_role;
grant execute on function public.admin_status_v1763() to authenticated,service_role;
grant execute on function public.admin_search_accounts_v1763(text) to authenticated,service_role;
grant execute on function public.admin_recent_actions_v1763() to authenticated,service_role;
grant execute on function public.admin_set_ban_v1763(uuid,integer,text) to authenticated,service_role;
grant execute on function public.admin_unban_user_v1763(uuid) to authenticated,service_role;
grant execute on function public.admin_reset_account_v1763(uuid) to authenticated,service_role;
grant execute on function public.admin_delete_account_v1763(uuid) to authenticated,service_role;
